language: python

python:
    - '3.8'

services:
    - docker

before_install:

install:
    - pip install -r requirements/requirements-dev.txt

env:
    global:
        - INDRA_HOME=/home/travis/build/gcallah/IndraABM
        - PYTHONPATH=$INDRA_HOME:$(pwd)
        - props_dir=$INDRA_HOME/APIServer/data/

script:
    - make tests

after_success:
    - ./deploy.sh
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - make prod_container
    - make deploy_container

notifications:
  slack: indras-net:QlnWeHMOpmEHCGJfG3SndDTr
