language: python

python:
    - '3.8'

services:
    - docker

before_install:

install:
    - pip install -r requirements/requirements-dev.txt

env:
    - INDRA_HOME=/home/travis/build/gcallah/IndraABM
    - PYTHONPATH=$INDRA_HOME:$(pwd) props_dir=/home/travis/build/gcallah/IndraABM/APIServer/data/

script:
    - make tests

after_success:

notifications:
  slack: indras-net:QlnWeHMOpmEHCGJfG3SndDTr
