language: python

python:
    - '3.8'

services:
    - docker

install:
    - pip install -r requirements-dev.txt
    - sudo apt-get update
    - sudo apt-get install sshpass

env:
    global:
        - INDRA_HOME=/home/travis/build/gcallah/IndraABM
        - PYTHONPATH=$INDRA_HOME:$(pwd)
        - props_dir=$INDRA_HOME/APIServer/data/

script:
    - make tests

after_success:
    - ./deploy.sh

notifications:
  slack: indras-net:QlnWeHMOpmEHCGJfG3SndDTr
