language: python

python:
    - '3.8'

services:
    - docker

before_install:

install:
    - pip install -r docker/requirements-dev.txt
    - cd webapp; npm install; cd /home/travis/build/gcallah/indraABM

env:
    - PYTHONPATH=/home/travis/build/gcallah/indraABM:$(pwd) props_dir=/home/travis/build/gcallah/indraABM/APIServer/data/

script:
    - make tests

after_success:

notifications:
  slack: indras-net:QlnWeHMOpmEHCGJfG3SndDTr
